### PR TITLE
Make the demo OSX friendly

### PR DESCRIPTION
**Pull request by theimowski**

### CODE REVIEW

**Comment by cmeeren** [comment]
Thanks! Are you fairly sure the changes won't negatively affect Windows/Linux?

**Comment by theimowski** [comment]
We have the same excerpt in [SAFE template](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/build.fsx#L5-L8) and haven't heard any complaints so far

**Comment by cmeeren** [comment]
Great, thanks again!

**Comment by theimowski** [comment]
You're welcome! Thanks for this sample code - makes really easy to get started with Fable and Electron

**Pull request merged**
