### PR TITLE
Fix 'Unsupported log file format' error by updating Fake.DotNet.cli

### PR DESCRIPTION
**Pull request by klettier**
## Summary

I just did a fresh clone and tried to build using **README** command

```
dotnet fake build -t Dev
```

And I ran into this error

image

Updating **Fake.DotNet.cli** resolved the issue

## Changes

* Update ```Fake.DotNet.cli``` package to ```5.20```
  * ```dotnet paket update Fake.DotNet.cli -g fakebuild```

### CODE REVIEW

**Comment by klettier** [comment]
I also updated ```Fable.Elmish.Debugger``` that updated ```Thoth.Json``` to resolve the build error below

```
FSC : error FS0193: The module/namespace 'Encode' from compilation unit 'Thoth.Json' did not contain the val 'ValLinkagePartialKey(generateEncoder)' [D:\code\fsharp\github\fable-elmish-electron-material-ui-demo\src\Renderer\Renderer.fsproj]
```

**Comment by klettier** [comment]
My advice would be to 'Build' the solution in the default target to avoid merging code that don't compile

**Comment by cmeeren** [comment]
Thanks! Not sure what you meant by that last comment. AppVeyor already builds PRs, and [the build for this PR seems to compile](https://ci.appveyor.com/project/cmeeren/fable-elmish-electron-material-ui-demo/builds/33083765). Are we good to merge then, or did you mean something else?

**Comment by cmeeren** [comment]
As a side note, I have just updated Fable.Electron for Electron 9, so I will be updating all other packages (npm and nuget) soon, too.

**Comment by klettier** [comment]
I meant running dotnet build on the solution, before my last commit dotnet build was failing but appveyor build didn't see anything

**Comment by cmeeren** [comment]
Ok, I'll let the build script be the boss, that's the supported way to build. :) Thanks a lot!

**Pull request merged**
